### ISSUE TITLE
Deprecate or redirect?

### ISSUE THREAD

**Issue by dojones1** [samdutton/mapTrack#1]
Hi Sam,

Short Story:
Can there be some documentation (Readme.md) here to indicate that a more up-to-date version of this code is now available as part of simpl.info? Or simply deprecate this and highlight in simpl.info that the mapTrack is there. Over time the google search rankings will push it up the search results.

Long Story:
I found your excellent html5rocks article on using track information with video I was particularly interested in the mention of the mapTrack demonstration, but had not found the version on. From what I can find this appears to be the best 'simple' example online of using track information to store metadata. This is very much aligned to something that I want to prototype, and was keen to know more. 

I downloaded this repository, thinking that it was the latest code base, (as it was not mentioned on the top level page at <simpl.info>. However I quickly found that the maptrack github code here was somewhat out out of date (still using TextTrackCue, the date field was not working). I was starting to get concerned that it might be a long struggle to get the full system working, when I happened to specifically google mapTrack, and found that it was available online at simpl.info. This made me dig further into the simpl.info github repository and eventually found the code there. All told I lost half a day.

Anyway the demo is great - I just want more people to find it more easily.

Donald

**Comment by samdutton** [comment]
Thanks Donald!  

Glad that you like the demo — sorry to hear you wasted time looking for the code.

I've added a note to the README.
